---
- hosts: all
  become: true

  tasks:
  - name: Check if alive
    ansible.builtin.ping:

  - name: Update all packages
    ansible.builtin.package:
      name: "*"
      state: latest

  - name: Show INSTALL_RKE2_TYPE value
    ansible.builtin.debug:
      msg: "The var INSTALL_RKE2_TYPE value is {{ lookup('ansible.builtin.env', 'INSTALL_RKE2_TYPE') }}"

  - name: Import the rke2 role
    import_role:
      name: rke2
